import defaultTheme from 'tailwindcss/defaultTheme';
import forms from '@tailwindcss/forms';
import containerQueries from '@tailwindcss/container-queries';

/** @type {import('tailwindcss').Config} */
export default {
    darkMode: 'class',

    content: [
        './vendor/laravel/framework/src/Illuminate/Pagination/resources/views/*.blade.php',
        './storage/framework/views/*.php',
        './resources/views/**/*.blade.php',
    ],

    theme: {
        extend: {
            colors: {
                'surface-variant': '#d8e3fb',
                'on-secondary-container': '#00714d',
                'deep-indigo': '#3730A3',
                'secondary-fixed-dim': '#4edea3',
                'primary-fixed': '#dde1ff',
                'error-crimson': '#EF4444',
                'secondary-fixed': '#6ffbbe',
                outline: '#757684',
                'primary-fixed-dim': '#b8c4ff',
                'on-background': '#111c2d',
                'surface-gray': '#F9FAFB',
                'on-primary-fixed-variant': '#173bab',
                'inverse-on-surface': '#ecf1ff',
                'on-primary-container': '#a8b8ff',
                'on-error': '#ffffff',
                error: '#ba1a1a',
                'on-secondary-fixed-variant': '#005236',
                'inverse-surface': '#263143',
                'tertiary-fixed-dim': '#ffb95f',
                'secondary-container': '#6cf8bb',
                'on-surface': '#111c2d',
                background: '#f9f9ff',
                'on-primary': '#ffffff',
                'outline-variant': '#c4c5d5',
                'on-tertiary-container': '#ffa929',
                primary: '#00288e',
                'surface-container-lowest': '#ffffff',
                'on-tertiary': '#ffffff',
                'on-tertiary-fixed': '#2a1700',
                surface: '#f9f9ff',
                'primary-container': '#1e40af',
                'tertiary-container': '#6b4200',
                'on-surface-variant': '#444653',
                'inverse-primary': '#b8c4ff',
                'surface-container-high': '#dee8ff',
                tertiary: '#4c2e00',
                'tertiary-fixed': '#ffddb8',
                'on-secondary': '#ffffff',
                'surface-dim': '#cfdaf2',
                secondary: '#006c49',
                'error-container': '#ffdad6',
                'on-error-container': '#93000a',
                'surface-tint': '#3755c3',
                'surface-container-low': '#f0f3ff',
                'on-tertiary-fixed-variant': '#653e00',
                'on-primary-fixed': '#001453',
                'surface-container-highest': '#d8e3fb',
                'on-secondary-fixed': '#002113',
                'surface-container': '#e7eeff',
                'surface-bright': '#f9f9ff',
                'accent-purple': '#B348C7',
            },
            borderRadius: {
                DEFAULT: '0.5rem',
                sm: '0.25rem',
                lg: '0.75rem',
                xl: '1rem',
                '2xl': '1.5rem',
                full: '9999px',
            },
            spacing: {
                'container-max': '1280px',
                base: '8px',
                'margin-desktop': '48px',
                gutter: '24px',
                'margin-mobile': '16px',
            },
            fontFamily: {
                sans: ['Inter', ...defaultTheme.fontFamily.sans],
                display: ['Lexend', 'sans-serif'],
                headline: ['Lexend', 'sans-serif'],
                body: ['Inter', 'sans-serif'],
                label: ['Inter', 'sans-serif'],
            },
        },
    },

    plugins: [forms, containerQueries],
};
